spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:qehbknvchsubzefksjdbc@db.mhfwztbedvxygqwptxpb.supabase.co:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:qehbknvchsubzefksjdbc}
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8080}  # Render injecte le PORT automatiquement